### ISSUE TITLE
Crear clase para que el elemento ocupe un 50% del ancho del contenedor

### ISSUE THREAD

**Issue by Alonso-Pablo** [RooftopAcademy/rooftstrap#100]
## Antes:
![Screenshot from 2021-11-08 12-16-08](https://user-images.githubusercontent.com/78811265/140768161-c4a30075-e9af-4e29-b389-cc1fd2ef30ef.png)

## Despues: 
![Screenshot from 2021-11-08 12-15-52](https://user-images.githubusercontent.com/78811265/140768215-5001d722-6b39-4be3-a07a-66499481ded5.png)

**Comment by smichelle05a** [comment]
Este issue se reemplaza con el nro 73
