### ISSUE TITLE
Cambiar el color de la clase `txt-light-grey` por uno mas claro

### ISSUE THREAD

**Issue by Alonso-Pablo** [RooftopAcademy/rooftstrap#103]
### Referencia:
![Screenshot from 2021-11-10 13-11-05](https://user-images.githubusercontent.com/78811265/141150290-6db02678-2f0f-4473-a081-d208b915dbaa.png)

**Comment by smichelle05a** [comment]
Este issue fue resuelto en #115

**Comment by smichelle05a** [comment]
Este issue fue resuelto en #115
