### ISSUE TITLE
Refactor de texttag-p

### ISSUE THREAD

**Issue by alezvi** [RooftopAcademy/rooftstrap#117]
duplicado en App.css
cambiar nombre por text-tag-p

**Comment by Alonso-Pablo** [comment]
No entiendo muy bien que hay que hacer.
El `texttag-p` solo existe en Rooftstore. ¿Hay que traerlo y ponerlo dentro de uno de los archivos de `Sass`?
¿Hay que modificar en Roofstore los duplicados?
Si es asi ¿Este Issue no tendria que estar en Roofstore en vez de aquí?

**Comment by smichelle05a** [comment]
Asociado con el issue #119
