### ISSUE TITLE
Crear una clase card

### ISSUE THREAD

**Issue by smichelle05a** [RooftopAcademy/rooftstrap#140]
Crear una clase card que sea un contenedor con fondo blanco, bordes redondeados grises y sombreado

**Comment by Alonso-Pablo** [comment]
¿Esto mismo no se puede hacer con las clases que ya tenemos?
Habíamos quedado que no se iba a enfocar en componentes sino en propiedades individuales

**Comment by Mauri548** [comment]
Esto habría que confirmarlo una vez que veamos si se puede hacer solo utilizando las clases que se van creando

**Comment by smichelle05a** [comment]
display: flex
border-radius: 6px
box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)
