### ISSUE TITLE
Agregar clases para pesos de fuentes

### ISSUE THREAD

**Issue by smichelle05a** [RooftopAcademy/rooftstrap#149]
- `txt-lighter`
- `txt-light`
- `txt-bold`
- `txt-bolder`

Se están usando los siguientes weight actualmente:

- `font-weight: 300`
- `font-weight: 400`
- `font-weight: 600`

**Comment by smichelle05a** [comment]
Revisar primero si hacen falta otros `font-weight`

**Comment by Alonso-Pablo** [comment]
Por ahora usamos los pesos: 300, 400, 500 y 600

**Comment by smichelle05a** [comment]
Agregar 200 y 800
