### ISSUE TITLE
fix: css property 

### ISSUE THREAD

**Issue by alezvi** [RooftopAcademy/rooftstrap#43]
https://github.com/RooftopAcademy/rooftstrap/pull/37/files#diff-4b1d306eb7949b768a10a68600e5973cdcbeafa0827e6f6e3c78c55269d4cc0bL108

La propiedad se utiliza como si fuera una variable.

La solucion seria crear la variable en la raiz:

`:root {
  --color-main: #EEEEEE;
}`

Y luego al utilizarlo:

`.bg-main {
  color : var(--color-main);
}`

**Comment by smichelle05a** [comment]
Este issue ya fue resuelto con anterioridad

**Comment by smichelle05a** [comment]
Este issue ya fue resuelto con anterioridad
