### ISSUE TITLE
Crear clase para tachar el texto dentro de una etiqueta

### ISSUE THREAD

**Issue by Alonso-Pablo** [RooftopAcademy/rooftstrap#56]
Hacer una clase `txt-strike` para **tachar el texto** que lo contenga: `text-decoration: line-through;`

Esta clase se usaría en los precios cuando hay descuentos:
![Screenshot from 2021-11-03 03-34-16](https://user-images.githubusercontent.com/78811265/140018059-d3edd70c-dc1d-428b-89d7-f43cdb3e075f.png)

**Comment by smichelle05a** [comment]
Este issue fue resuelto con anterioridad
