### ISSUE TITLE
Crear una clase para quitar el padding base de un contenedor

### ISSUE THREAD

**Issue by Alonso-Pablo** [RooftopAcademy/rooftstrap#59]
Crear una clase para **quitar/sobrescribir el padding** por defecto de base que tiene un contenedor al usar las clases `row` y/o `col`. Escribir la clase por debajo de la línea donde se declaran las clases `row` y `col` para que puedan sobrescribir a estas.
(`padding: 0` o `padding: unset` discutirlo con el scrum master)

**Comment by smichelle05a** [comment]
Este issue ya fue resuelto con anterioridad
