### ISSUE TITLE
Crear clases para el acomodamiento de los elementos hijos 

### ISSUE THREAD

**Issue by Alonso-Pablo** [RooftopAcademy/rooftstrap#60]
- [ ] Crear una clase `d-flex`  para dar la propiedad y valor: `display:flex;`

- [ ] Crear una clase  (por ejemplo: `v-hidden`) para ocultar visiblemente un elemento de la vista del usuario.
`visibility: hidden;`

- [x] Crear una clase  (por ejemplo: `f-wrap`) para hacer que si los hijos del contenedor no tienen suficiente espacio hacia la derecha **se bajen a la fila de abajo**. 
`flex-wrap: wrap`

- [ ] Crear una clase (por ejemplo: `jc-center`) para **centrar el contenido**. 
`justify-content: center;`.

- [ ]  Crear una clase (por ejemplo: `ai-center`) para **centrar el contenido**. 
`align-items: center;`.

- [x] #84
`flex-direction: column`.

**Comment by smichelle05a** [comment]
Este issue se reemplaza con el nro 136
