### ISSUE TITLE
Crear clases para sobrescribir los h1, h2,... etc por defecto.

### ISSUE THREAD

**Issue by pablocanale** [RooftopAcademy/rooftstrap#68]
Quizas usar class tittle...

Hacer un estilo para los h1, font weight 600, y font size 1.25REM puede ser. 

![image](https://user-images.githubusercontent.com/70720691/140393894-fe123f92-2610-493f-899d-5033474c82ff.png)

**Comment by smichelle05a** [comment]
Este issue ya fue resuelto
