### ISSUE TITLE
Crear clases para definir el ancho porcentual de las columnas relativo al ancho de una fila

### ISSUE THREAD

**Issue by feralba28** [RooftopAcademy/rooftstrap#73]
Crear clases para utilizar las 12 columnas con flex

**Comment by smichelle05a** [comment]
Columnas:

12 { width: 100% }
11 { width: 91% }
10 { width: 83% }
9 { width: 75% }
8 { width: 66% }
7 { width: 58% }
6 { width: 50% }
5 { width: 41% }
4 { width: 33% }
3 { width: 25% }
2 { width: 16% }
1 { width: 8% }
